### ISSUE TITLE
Searching for samplers

### ISSUE THREAD

**Issue by chrishughw** [SteveMcGrath/bidhistory#2]
Hi!  This kinda may be the same issue as the last issue.  Ive tried to search with identifying the category as sampler and it just isn't working for me.  I really expect its a user error, with the issue being not entering the search string and modifier correctly. Here is the item I am trying to search for-

http://www.cigarbid.com/auction/lot/2177974

I really appreciate your taking this and running with it, I can't even guess just how much money sloppy saved me over the past several years and expect the same savings based upon your hard work in the future!  I would happily purchase a membership or donate to defray any cost or reward your labor!  Heck, perhaps better, we could send a few cigar bombs your way! Whatcha like?

**Comment by SteveMcGrath** [comment]
So I applied a fix to allow the backend to bypass samplers when a full search is specified.  The sampler in particular that you pointed out is the first time that it has been seen, hence no data however.

**Comment by chrishughw** [comment]
Interesting, so the database doesn't capture auctions unless someone makes
requests for the history?  This cigar combo has run at least twice a week
for months, if not years on cigarbid.

Thanks!!!

**Comment by SteveMcGrath** [comment]
do you have some examples of earlier auctions with the same sampler?

**Comment by chrishughw** [comment]
Here's three earlier lots, I am sure I can find more if you need them.

http://www.cigarbid.com/Auction/Lot/2137355

http://www.cigarbid.com/Auction/Lot/2132799

https://www.cigarbid.com/Auction/Lot/2106776

Thx!

**Comment by chrishughw** [comment]
I actually found a couple others like this that where not showing up... But then lost them!  Augh, will try again later.  The interesting similarity was that they all started with "#22" with the 22 being any number.  Also, all the samplers I search for using this awesome history showed up without the need to specify the sampler category.  The history even stated it was a sampler.  More interesting, all the samplers I found the history of did not have the "#xx" in the cbid name.

**Comment by chrishughw** [comment]
Rereading this, I am not sure I explained myself well, I struggle with English (even if it is my native language)!  But in a nutshell, most the samplers named something like "rock Patel broad length flight" or any other just letters showed up in the search.  The ones named "#69 coa alaskian sun grown maduro" don't seem to appear no matter if I specify category=sampler or not.

I am sorry for being so backward!  :)

**Comment by SteveMcGrath** [comment]
Now this makes more sense.  if this is the case, then its an issue with the regex patterns.

**Comment by SteveMcGrath** [comment]
Lets see if that helps anything along...
