### ISSUE TITLE
The security cert for herf.io is expired. 

### ISSUE THREAD

**Issue by b4t2XqejWpDl** [SteveMcGrath/bidhistory#4]
The security cert for herf.io is expired resulting in errors for the Cigar Price History chrome plugin that pulls from herf.io

![image](https://user-images.githubusercontent.com/42924122/44967043-a22b1180-af0c-11e8-8743-1784367f7b4d.png)

**Comment by SteveMcGrath** [comment]
looks like certbot had changed the name of the cert on me....should work now.
